name: venv
channels:
  - conda-forge
dependencies:
  - pip
  - python>=3.8
  - nbconvert
  - r-lubridate
  - r-stringr
  - r-jsonlite
  - r-dplyr
  - r-glue
  - r-magrittr
  - r-purrr
  - r-aws.s3
  - r-tidyr
  - r-tibble
  - r-SecretsProvider
  - r-httr
  - r-cli
  - r-xml2
  - papermill
  - ipykernel